// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/harisaginting/tech-test-adsi/api/v1/cases"
)

// Injectors from wire.go:

func ApiCases() cases.Controller {
	service := cases.ProviderService()
	controller := cases.ProviderController(service)
	return controller
}
