// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/harisaginting/ginting/api/v1/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func ApiUser(db *gorm.DB) user.Controller {
	repository := user.ProviderRepository(db)
	service := user.ProviderService(repository)
	controller := user.ProviderController(service)
	return controller
}
